### ISSUE TITLE
[ENH] enable export of a single zip file with all of a subject's sessions in it

### ISSUE THREAD

**Issue by mattcieslak** [PennBBL/fw-heudiconv#13]
Running fmriprep on a single session might not be possible (eg if there is only a single T1 acquired per subject over many sessions). 

We should be able to get all of a subject's sessions into one zip archive that can then be sent to fmriprep.

**Comment by hkethi002** [comment]
the [flywheel-bids](https://pypi.org/project/flywheel-bids/) library has an export function to export a subject from flywheel into bids if its curated in flywheel.

**Comment by TinasheMTapera** [comment]
Suggest we close this one then

**Comment by mattcieslak** [comment]
We're going around the flywheel-bids package at the moment because we want to make sure we can get the extended bids data like asl and qsm.
