### ISSUE TITLE
TaskName field not getting filled

### ISSUE THREAD

**Issue by willtack** [PennBBL/fw-heudiconv#20]
It looks like the "TaskName" field in the json sidecar for functional images is not getting filled out by the converter. I tried a few sessions in multiple projects. I think TaskName correlates with the Task field in the Flywheel web interface's info box for a given acquisition, and those are empty too. 

Attaching an example json (as a .txt)

[sub-P68_ses-01_task-sentence_bold.txt](https://github.com/PennBBL/fw-heudiconv/files/3164112/sub-P68_ses-01_task-sentence_bold.txt)

Again, maybe doing something wrong

**Comment by mattcieslak** [comment]
Thanks for reporting, this is a bug. These BIDS fields in the flywheel website aren't actually used by any of the BIDS gears (they're just for the layout and maybe searches).

Does the lack for a TaskName field in the sidecar cause gears to crash?

**Comment by willtack** [comment]
fmriprep was crashing for me. I manually filled in the Task field in the BIDS section of the info module and ran fmriprep again. It's still going but it hasn't crashed yet, whereas the previous run ended in 30 seconds.

The only other thing that would be different was that the first time I ran the gear I didn't see a field for FREESURFER_LICENSE in the configuration. Oddly 40 minutes later, there was and that's the run still going. 

I'll attach screenshots.

![gear_run1](https://user-images.githubusercontent.com/48965778/57539368-5ab91880-7318-11e9-9eb3-54badc3856b9.png)
![gear_run2](https://user-images.githubusercontent.com/48965778/57539374-5d1b7280-7318-11e9-8683-082014a49986.png)

**Comment by TinasheMTapera** [comment]
Hey @willtack , 

I've updated `fw-heudiconv` on pip. The gear should pull the new version (0.0.8) which automatically fills in all relevant fields in the sidecar, based on fields in the heuristic that the user specifies. Try it out and let me know how it goes

**Comment by willtack** [comment]
@TinasheMTapera ,

Tried it out and all the relevant fields are now getting filled! (Including TaskName)
