### ISSUE TITLE
[ENH] Add a default reproin heuristic

### ISSUE THREAD

**Issue by mattcieslak** [PennBBL/fw-heudiconv#23]

**Comment by mattcieslak** [comment]
Ideas:

 1. Make it a commandline option: just have some basic pattern matching that ignores fieldmaps
 2. Make it an importable function that can be included in a heuristic. Something like:

```
from fw_heudiconv import reproin

infotodict = reproin

IntendedFor = { ... }
MetadataExtras = { ... }
```

**Comment by TinasheMTapera** [comment]
@mattcieslak went over our options today. I like the importable function option as it's less overhead. In fact, if they want to add it in their .py, then it's simply a matter of them knowing how to import it from heudiconv. You can do it like this:

```
import importlib

module = importlib.import_module('heudiconv.heuristics.{}'.format(<heuristic_in_heudiconv>))
infotodict = module.infotodict
```

So in the CLI there's really not much to change. The next thing I'll be working on is how to add this as an option in the gear

**Comment by TinasheMTapera** [comment]
Should work now, keeping the [branch](https://github.com/PennBBL/fw-heudiconv/tree/ttapera-reproin) separate for a little in case something comes up
