### ISSUE TITLE
discriminate based on dimensions

### ISSUE THREAD

**Issue by willtack** [PennBBL/fw-heudiconv#25]
Hi,

I'm trying to discriminate between two sequences where the only difference is in the image dimensions, which I can see in the seqinfo tsv file. However, I'm encountering this error: 

INFO: Loading heuristic file...
INFO: Applying heuristic to query results...
Traceback (most recent call last):
  File "./fw_heudiconv_run.py", line 69, in <module>
    curate.convert_to_bids(fw, project_label, heuristic, subjects, sessions, dry_run=dry_run)
  File "/flywheel/v0/fw_heudiconv/cli/curate.py", line 86, in convert_to_bids
    to_rename = heuristic.infotodict(seq_infos)
  File "/flywheel/v0/input/heuristic/presurgicalEpilepsy_heuristic_5.py", line 96, in infotodict
    if dim3==612:
NameError: name 'dim3' is not defined

Attaching the seq info file. I'm trying to discriminate between an ASL sequence and its corresponding M0 scan. The dcm2niix conversion seems messy because there are two separate nifti files for the M0. I'll poke around to see if that might be the more fundamental issue, because the conversion goes fine outside of Flywheel.

[presurgicalEpilepsy_SeqInfo.xlsx](https://github.com/PennBBL/fw-heudiconv/files/3335986/presurgicalEpilepsy_SeqInfo.xlsx)

FYI I accidentally posted an empty issue a few minutes ago; sorry about that.

**Comment by TinasheMTapera** [comment]
Could you send the heuristic? It might be a python syntax thing

**Comment by willtack** [comment]
[presurgicalEpilepsy_heuristic.txt](https://github.com/PennBBL/fw-heudiconv/files/3336420/presurgicalEpilepsy_heuristic.txt)

FWIW, the ideal way to decide would be with the number of timepoints (aka dim4) but that is listed as -1 for all sequences in the tsv?

**Comment by TinasheMTapera** [comment]
You gotta wrap you `dim3`'s in quotes, otherwise they're interpreted as variables (which you haven't set).

```
# if dim3==612: # nope
if "dim3"==612:
```

**Comment by willtack** [comment]
Right, okay. My bad. Thanks!

Re: dim4 what do you think might be going on there?

**Comment by mattcieslak** [comment]
Are you sure, @TinasheMTapera? I don't think `"dim3"==612` will ever be true. I think you want to check if `s.dim3 == 612`. dim4 is a known problem with flywheel (see #8), we're waiting to hear from them for a solution.

**Comment by TinasheMTapera** [comment]
@mattcieslak is right, I spoke too soon

**Comment by willtack** [comment]
Got it. Thanks all!
