### ISSUE TITLE
tabulate.py / tsv file won't recognize both scan 1 and scan 2 data from same session

### ISSUE THREAD

**Issue by bbiney73** [PennBBL/fw-heudiconv#38]
There's a subject that I"m going to arbitrarily call subj 009. We've been using the tabulate command via Flywheel's commandline interface. 
subj 009 has one session in which two scans took place at different time points in the session, scan 1 and scan 2.

Just for clarification:
Scan 1 - we put someone in the scanner and they come out.

Scan 2 - the same person that did scan 1 gets put back into the scanner for scan 2

the tabulate.py command is not generating a tsv file that contains sequences to identify both scan 1 and scan 2. Only scan 1 is included. 
We haven't been able to find a log file for tabulate.py either so we're not sure how to debug

Multiple subjects like subj 009 have two scans in their session, so we have to resolve this.

**Comment by TinasheMTapera** [comment]
Hey @bbiney73,

Please upgrade your `fw-heudiconv` to the latest version by doing:

```
pip install fw-heudiconv --upgrade
```

Should take you to development version 19, where you'll have the option to add a flag `--no-unique`. This will ensure you get every line in the table that summarises your dataset, as opposed to filtered by unique combinations of sequence data. Code changes here 06a74291ae2ac5f5116dcf886b6bad6aa946cd8c
