### ISSUE TITLE
[BUG] dataset_description.json values get overwritten if they exist

### ISSUE THREAD

**Issue by mattcieslak** [PennBBL/fw-heudiconv#57]
https://github.com/PennBBL/fw-heudiconv/blob/2b6214cc5b2cf398a794c22b1e92c0ddbf6aa09e/fw_heudiconv/convert.py#L315

**Comment by TinasheMTapera** [comment]
Haha yeah....... I remember wondering whether or not people would have defaults and I leaned on no... time to update

**Comment by TinasheMTapera** [comment]
This should be solved here
https://github.com/PennBBL/fw-heudiconv/blob/dc36e76d057ab9113afde3d42ecd11777a936955/fw_heudiconv/convert.py#L313
