### ISSUE TITLE
[ENH] Add option for alternative session label

### ISSUE THREAD

**Issue by mattcieslak** [PennBBL/fw-heudiconv#7]
Add option to change ses- to something consistent across the whole study. Session labels are not useful

**Comment by TinasheMTapera** [comment]
possible conflict with 

> `RenameSubject()` and `RenameSession()` function in the heuristic will solve lots of our problems with bad subject/session names

**Comment by TinasheMTapera** [comment]
Add to heuristic metadata to be processed by `apply_heuristic`

- session_renamer()
- subject_renamer()
