### ISSUE TITLE
Add ASL functionality as basic module

### ISSUE THREAD

**Issue by TinasheMTapera** [PennBBL/fw-heudiconv#72]
Using https://github.com/PennLINC/aslbids

This functionality should allow users curating ASL data to have a function that:

1. Generates the ASL metadata sidecar using a specified metadata json file
2. Generates the ASL .tsv that accompanies scans automatically from this json

TODO:

- [ ] create a function that replicates https://github.com/PennLINC/aslbids/blob/master/edit_aslbids.py and can produce a json with all of the added data
- [ ] in the heuristic, add a function that parses the metadataextras section using above function
- [ ] in the heuristic, add a function that can write/overwrite a tsv at runtime

@a3sha2

**Comment by mflounders** [comment]
Let me know if you want to work together on this. I may be able to help and am testing out `aslprep` with local asl data and utilizing `aslbids` along the way

**Comment by TinasheMTapera** [comment]
Totally @mflounders! I am not actively working on this issue at the moment but if you want to pick it up I'm happy to look into it.

**Comment by TinasheMTapera** [comment]
Done 9ad2123
